name: Extract and update summary

on:
  push:
    paths:
      - 'zips/*.zip'

permissions:
  contents: write

jobs:
  process-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Remove deleted processes
        run: |
          shopt -s nullglob
          for dir in docs/processus/*; do
            [ -d "$dir" ] || continue
            name=$(basename "$dir")
            if [ ! -f "zips/$name.zip" ]; then
              rm -rf "$dir"
            fi
          done

      - name: Extract zip files
        run: |
          mkdir -p extracted
          shopt -s nullglob
          for file in zips/*.zip; do
            name=$(basename "$file" .zip)
            mkdir -p "docs/processus/$name"
            unzip -o "$file" -d "extracted"
            inner=$(unzip -Z1 "$file" | head -1 | cut -d/ -f1)
            mv "extracted/$inner/"* "docs/processus/$name/"
            rm -rf extracted/*
          done

      - name: Generate processus.json
        run: |
          echo "[" > docs/processus.json
          first=true
          for dir in docs/processus/*; do
            [ -d "$dir" ] || continue
            name=$(basename "$dir")
            title=$(echo "$name" | sed -e 's/-/ /g' -e 's/\b\(.\)/\u\1/g')
            category=$(echo "$name" | cut -d'-' -f1)
            $first || echo "," >> docs/processus.json
            first=false
            cat <<EOF >> docs/processus.json
          {
            "title": "$title",
            "link": "./processus/$name/index.html",
            "category": "$category"
          }
          EOF
          done
          echo "]" >> docs/processus.json

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add docs/
          git commit -m "Mise à jour automatique du sommaire"
          git push
